import { Component } from '@angular/core';
import {
  UnicoCheckBuilder,
  SelfieCameraTypes,
  UnicoThemeBuilder,
} from 'unico-webframe';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'unico-webframe-poc-angular';

  ngOnInit(){
    const unicoCameraBuilder = new UnicoCheckBuilder();
    unicoCameraBuilder.setModelsPath(this.getHostUrlBase('assets/models'));

    const callback = {
      on: {
        success: (obj: any) => {
          console.log(obj.base64);
        },
        error: (error: any) => {
          console.error(error);
        },
      },
    };

    const unicoTheme = new UnicoThemeBuilder()
      .setColorSilhouetteSuccess('#0384fc')
      .setColorSilhouetteError('#D50000')
      .setColorSilhouetteNeutral('#fcfcfc')
      .setBackgroundColor('#dff1f5')
      .setColorText('#0384fc')
      .setBackgroundColorComponents('#0384fc')
      .setColorTextComponents('#dff1f5')
      .setBackgroundColorButtons('#0384fc')
      .setColorTextButtons('#dff1f5')
      .setBackgroundColorBoxMessage('#fff')
      .setColorTextBoxMessage('#000')
      .setHtmlPopupLoading(
        `<div style="position: absolute; top: 45%; right: 50%; transform:
translate(50%, -50%); z-index: 10; text-align: center;">Carregando...</div>`
      )
      .build();

    unicoCameraBuilder.setTheme(unicoTheme);

    const unicoCamera = unicoCameraBuilder.build();

    const cameraPromised = unicoCamera.prepareSelfieCamera(
      '/services.json', // MISSING FILE: is generated by UNICO platform
      SelfieCameraTypes.SMART
    );

    document.addEventListener("DOMContentLoaded", () => {
    cameraPromised.then((cameraOpener: any) =>
      cameraOpener.open(callback)
    );
    });

  }

  private getHostUrlBase(path: string) {
    return window.location.protocol + "//" + window.location.host + "/" + path;
  }

}